### ISSUE TITLE
Change starting global depth

### ISSUE THREAD

**Issue by Fiskeboat** [devimam/exhash#1]
Hey! Do you think it would be possible to change the starting global depth, i?
So that it started at i = 2 instead?
00
01
10
11
Like that? Thanks.

**Comment by devimam** [comment]
According to the extendible hash concept at first, it will allocate as low space as possible for memory efficiency. Then it will grow dynamically with a power of 2. So in the beginning, the value of i should be 1.

The simulator is made based on this concept.
